### ISSUE TITLE
Add an option to allow beds to function normally.

### ISSUE THREAD

**Issue by DesolateIntention** [friedkeenan/chronopyre#5]
As a suggestion, I would like to still be able to sleep in beds. I like the resting mechanic but I'll have to remove the mod because I don't want to give up on beds.

**Comment by friedkeenan** [comment]
Sorry, for me the point of this mod is to replace beds as a mode of advancing time, and making it an option that you could still use beds would place more maintenance burden on me for a feature that for me would defeat the purpose of the mod anyways. So, I won't be adding an option, sorry.

I could probably see me making it so the player can still actually *get in* the bed and it just wouldn't advance time (but would probably still affect the phantom timer) but that isn't what you want.

Thanks for checking out the mod anyways, I really do appreciate it.
